source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.1'

pod 'PPRevealSideViewController', '~> 1.2.0'
pod 'AFNetworking', '~> 2.0'
pod 'SDWebImage', '~> 3.7'
pod 'IDMPhotoBrowser', '~> 1.3'
pod 'UICKeyChainStore'
pod 'Facebook-iOS-SDK', '~> 3.15'
pod 'Mixpanel'
pod 'JTHelper', '~> 0.1.1'
pod 'PonyDebugger'
pod 'SMPageControl'
pod 'PPHelpMe'
pod 'HHRouter', '~> 0.1'
pod 'TTTAttributedLabel'
pod 'NSDate+Calendar'
pod 'MZFormSheetController'
pod 'JTSImageViewController'
pod 'EAIntroView'

link_with 'Flooz', 'Flooz dev', 'Flooz local', 'FloozTests'