source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'

pod 'AFNetworking'
pod 'SDWebImage'
pod 'IDMPhotoBrowser'
pod 'UICKeyChainStore'
pod "FBSDKCoreKit"
pod "FBSDKLoginKit"
pod "FBSDKShareKit"
pod "FBSDKMessengerShareKit"
pod 'Mixpanel'
pod 'JTHelper', '~> 0.1.1'
pod 'PonyDebugger'
pod 'SMPageControl'
pod 'PPHelpMe'
pod 'HHRouter', '~> 0.1'
pod 'TTTAttributedLabel'
pod 'NSDate+Calendar'
pod 'MZFormSheetController'
pod 'JTSImageViewController'
pod 'EAIntroView'
pod 'JPSVolumeButtonHandler'
pod 'ActionSheetPicker-3.0'
pod 'iCarousel'
pod 'FXBlurView'
pod 'Branch'
pod 'GBDeviceInfo'
pod 'RDVTabBarController'
pod 'Crashlytics'
pod 'Fabric'
pod 'HMSegmentedControl'
pod 'VCTransitionsLibrary'
pod 'Stripe'
pod 'libPhoneNumber-iOS'

link_with 'Flooz', 'Flooz dev', 'Flooz local', 'FloozTests'